// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('tmsApp').controller('LoginCtrl', [
    '$scope', '$location', '$http', 'tmsUtil', function($scope, $location, $http, tmsUtil) {
      var init;
      $scope.userEntity = {
        username: '',
        password: '',
        rememberMe: false
      };
      $scope.doLogin = function() {
        return $http.post(Tms.apiAddress + "/api/user/login", {
          username: $scope.userEntity.username,
          password: $scope.userEntity.password
        }).then(function(res) {
          var token;
          if ($scope.userEntity.rememberMe) {
            localStorage.setItem('username', $scope.userEntity.username);
          } else {
            localStorage.removeItem('username');
          }
          token = res.data.token;
          $http.defaults.headers.common['x-token'] = token;
          localStorage.setItem('x-token', token);
          return $location.path('/').replace();
        }, tmsUtil.processHttpError);
      };
      init = function() {
        var username;
        username = localStorage.getItem('username');
        if (username) {
          $scope.userEntity.rememberMe = true;
          return $scope.userEntity.username = username;
        }
      };
      return init();
    }
  ]);

}).call(this);

//# sourceMappingURL=loginCtrl.js.map
