// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('tmsApp').controller('IndexCtrl', [
    '$scope', '$location', '$http', 'tmsUtil', function($scope, $location, $http, tmsUtil) {
      var init;
      $scope.task = {
        taskName: ''
      };
      $scope.taskList = [];
      init = function() {
        console.log(2);
        return $http.get(Tms.apiAddress + "/api/task").then(function(res) {
          var tasks;
          tasks = res.data;
          return $scope.taskList = tasks;
        }, tmsUtil.processHttpError);
      };
      $scope.exit = function() {
        return $http.post(Tms.apiAddress + "/api/user/logout").then(function() {
          alert('Logout succeed.');
          return $location.path('/login');
        }, tmsUtil.processHttpError);
      };
      $scope.changeTaskStatus = function(task) {
        return task.status = task.checked ? 'Finish' : 'InProgress';
      };
      $scope.deleteTask = function(task, index) {
        task.deleted = trues;
        return $http.put(Tms.apiAddress + "/api/task", task).then(function() {
          return $scope.taskList.splice(index, 1);
        }, tmsUtil.processHttpError);
      };
      $scope.editTask = function(task) {
        task.isEditing = true;
        return task.tempTaskName = task.taskName;
      };
      $scope.cancelEditTask = function(task) {
        return task.isEditing = false;
      };
      $scope.saveTask = function(task) {
        var oldTaskName;
        oldTaskName = task.taskName;
        task.taskName = task.tempTaskName;
        return $http.put(Tms.apiAddress + "/api/task", task).then(function(res) {
          return task.isEditing = false;
        }, function(res) {
          task.taskName = oldTaskName;
          return tmsUtil.processHttpError(res);
        });
      };
      $scope.addTask = function() {
        var task;
        task = angular.copy($scope.task);
        return $http.post(Tms.apiAddress + "/api/task", {
          taskName: task.taskName
        }).then(function(res) {
          var newTask;
          newTask = res.data;
          task._id = newTask._id;
          task.deleted = newTask.deleted;
          $scope.taskList.push(task);
          return $scope.task.taskName = '';
        }, tmsUtil.processHttpError);
      };
      return init();
    }
  ]);

}).call(this);

//# sourceMappingURL=indexCtrl.js.map
