// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('tmsApp').controller('RegisterCtrl', [
    '$scope', '$http', '$location', 'tmsUtil', function($scope, $http, $location, tmsUtil) {
      $scope.userEntity = {
        username: '',
        password: '',
        password2: ''
      };
      return $scope.doRegister = function() {
        if ($scope.userEntity.password !== $scope.userEntity.password2) {
          return alert('两次密码不一致');
        }
        return $http.post(Tms.apiAddress + "/api/user/register", {
          username: $scope.userEntity.username,
          password: $scope.userEntity.password2
        }).then(function(res) {
          alert('注册成功！');
          return $location.path('/login');
        }, tmsUtil.processHttpError);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registerCtrl.js.map
